[2025-01-11 20:43:55] This is std::cout 
[2025-01-11 20:43:55] This is std::cerr 
[2025-01-11 20:43:55] EXCEPTION CAUGHT: std::runtime_error - This error should be written in the log file
